
FROM gidhome/docker-unix-developer
MAINTAINER gid@gid.cimne.upc.edu

# Set correct environment variables
ENV HOME /root
ENV DEBIAN_FRONTEND noninteractive
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV TZ=Europe/Madrid
ENV SCREEN_RESOLUTION 1280x800

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Installing apps (Note: git is here just in case noVNC needs it in launch.sh
RUN apt-get -y install apt-utils
RUN apt-get update && apt-get -y install \
	xvfb \
	x11vnc \
	supervisor \
	fluxbox	\
	net-tools \
	git-core \
	git

###         libglu1-mesa \
###         libharfbuzz0b
# x11-server-utils to install  xrandr

# House cleaning
RUN apt-get autoclean

# Docker's supervisor
COPY supervisord-gidhome.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /root/
COPY create-basic-preferences.sh /root/
RUN chmod 755 /root/create-basic-preferences.sh
RUN /root/create-basic-preferences.sh
RUN rm /root/create-basic-preferences.sh

# Set display
ENV DISPLAY :0

WORKDIR /root
# ADD noVNC-0.6.2 /root/novnc/
# RUN ln -s /root/novnc/vnc_auto.html /root/novnc/index.html 
ADD noVNC-1.1.0 /root/novnc/
RUN ln -s /root/novnc/vnc_lite.html /root/novnc/index.html 

# Expose Port (Note: if you change it do it as well in surpervisord.conf)
# **port 8083** is the http://xxx:8083 vnc-like visualization of GiD application in a graphical environment
# **port 15818** is the http:// image-server of GiD
# **port 6900** is GiD's own communication protocol to enable gid-client <----> gid-server communication
EXPOSE 8083 15818 6900

CMD ["/usr/bin/supervisord"]
